name: RLS-314-2023 CI/CD

on:
  create:
    branches:
    - RLS-*
  pull_request:
    branches:
    - master

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    outputs:
      buildVersion: ${{ steps.buildGame.outputs.buildVersion }}
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows # Build a Windows standalone.
          # - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          # - StandaloneWindows64 # Build a Windows 64-bit standalone.
          # - StandaloneLinux64 # Build a Linux 64-bit standalone.
          # - iOS # Build an iOS player.
          # - Android # Build an Android .apk standalone app.
          # - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        id: buildGame
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          buildName: ${{ env.BRANCH_NAME }}-v${{ steps.buildGame.outputs.buildVersion }}
      - run: echo "ProjectVersion:${{ steps.buildGame.outputs.buildVersion }}"
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ env.BRANCH_NAME }}-v${{ env.BRANCH_NAME }}
          path: build/${{ matrix.targetPlatform }}
  
  task-automation:
    needs: build
    runs-on: ubuntu-latest
    name: Post Task Automation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Task Automation
        uses: 314-studio/314-automation@main
        id: j1p1
        with:
          m2m-314-automation-secret: ${{ secrets.M2M_314_AUTOMATION_SECRET }}
          m2m-314-automation-base-url: ${{ secrets.M2M_314_WORKFLOW_URL_BASE }}
          trello-list-name-under-review: ${{ vars.TRELLO_LIST_NAME_UNDER_REVIEW }}
          trello-list-name-in-progress: ${{ vars.TRELLO_LIST_NAME_IN_PROGRESS }}
          workflow-id: ${{ github.run_id }}
          build-version: ${{ needs.build.outputs.buildVersion }}
