name: branch automation

on:
  create:
    branches:
      - RLS-*

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  task-automation:
    runs-on: ubuntu-latest
    name: Post branch creation trello automation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Task Automation
        uses: 314-studio/314-automation@main
        id: j1p1
        with:
          m2m-314-automation-secret: ${{ secrets.M2M_314_AUTOMATION_SECRET }}
          m2m-314-automation-base-url: ${{ secrets.M2M_314_WORKFLOW_URL_BASE }}
          trello-list-name-under-review: ${{ vars.TRELLO_LIST_NAME_UNDER_REVIEW }}
          trello-list-name-in-progress: ${{ vars.TRELLO_LIST_NAME_IN_PROGRESS }}
          build-file-name: ${{ needs.build.outputs.filename }}
          build-version: ${{ needs.build.outputs.buildVersion }}
